### ISSUE TITLE
关于mellotron multi-speaker训练的问题

### ISSUE THREAD

**Issue by segmentationFaults** [KuangDD/zhrtvc#109]
hello， 您好，感谢您的开源。 
最近开始入门TTS， 正在尝试使用您的mellotron mspk 模式训练aishell3.
有以下几个问题请教：
1.  validation 声谱图看起来很相近， 听pred的声音也没什么问题， 但是alignment 一团糟是为什么？
![image](https://user-images.githubusercontent.com/63061001/117530064-b43ea580-b00d-11eb-92e8-acf6f09f4226.png)
2. hparams 里面的n_speakers 是什么意思， 设置为训练集中的speaker个数报错
3. 按照您在文档里提到的数据格式
![image](https://user-images.githubusercontent.com/63061001/117530135-14354c00-b00e-11eb-92f2-8be6c870b0b8.png)
貌似speaker_id 都是0， 这样没有问题吗？（我是看了下代码， 然后在metadata.csv后面加了一列 speaker）

**Comment by KuangDD** [comment]
用aishell3训练不建议用mspk模式，因为每个发音人语料数量少，不足以支撑起一个发音人。

mspk模式的多发音人的，每个发音人对应一个发音人向量（有speaker名称决定），在每个发音人都有足够语料的情况下使用，例如每个发音人都有至少1小时的语音。

用aishell3训练，建议用rtvc模式，这个模式可以每个发音人数量相对较少，这个模式每个音频都会转为音频向量（类似于发音人向量），模型的泛化能力能够更有效整个所有发音人的语音和文本的对齐。

图中的情况明显过拟合，模型参数量大，而数据量少（每个发音人），alignment不用对齐loss也能很低，但是训练集外的就会合成很差。

用rtvc模式试试，会更加合适。

**Comment by segmentationFaults** [comment]
您好， 上周末开始训练rtvc模式， batch_size=32, 目前迭代了60k部， alignment 依然是乱的， 需要继续迭代下去吗？ 我看loss在0.2～0.3 之间波动很久了
![image](https://user-images.githubusercontent.com/63061001/117610127-cd715e80-b193-11eb-8e96-5a87c47d4cb2.png)

**Comment by lgf821793883** [comment]
> hello， 您好，感谢您的开源。
> 最近开始入门TTS， 正在尝试使用您的mellotron mspk 模式训练aishell3.
> 有以下几个问题请教：
> 
> 1. validation 声谱图看起来很相近， 听pred的声音也没什么问题， 但是alignment 一团糟是为什么？
>    ![image](https://user-images.githubusercontent.com/63061001/117530064-b43ea580-b00d-11eb-92e8-acf6f09f4226.png)
> 2. hparams 里面的n_speakers 是什么意思， 设置为训练集中的speaker个数报错
> 3. 按照您在文档里提到的数据格式
>    ![image](https://user-images.githubusercontent.com/63061001/117530135-14354c00-b00e-11eb-92f2-8be6c870b0b8.png)
>    貌似speaker_id 都是0， 这样没有问题吗？（我是看了下代码， 然后在metadata.csv后面加了一列 speaker）

能加个qq 或者 微信聊一下嘛，我最近也在搞这个。
