### ISSUE TITLE
去掉gst的原因

### ISSUE THREAD

**Issue by yyq90** [KuangDD/zhrtvc#116]
你好大佬，我看了mellotron的readme中的实验日志，想必有不少经验，有2个问题想请教：
1、为什么要去掉gst模块，加上会出现什么样的效果呢；
2、speaker_emb从原来的128降到了64，这里的原因是什么呢，是否是根据数据集speaker数量减少所作的调整，我在自己的数据集上训练，这个参数有优化空间吗？

**Comment by KuangDD** [comment]
1. gst模块号称是调控语音韵律风格的模块，但是实验中发现这个模块结合其他模块时候，作用不明显，更多的是调控音色，而且不稳定，即调控的音色或韵律都没有预期效果，所以去除。
2. speaker embed是会和文本的embed拼接的，如果维度太大，则容易让文本的信息被掩盖，带来噪声，更难收敛。speaker embed可以用更能表示音色的方案去做。
