### ISSUE TITLE
如何使用智浪淘沙训练和分享的模型

### ISSUE THREAD

**Issue by jthinking** [KuangDD/zhrtvc#45]

**Comment by KuangDD** [comment]
同样的方法放到指定目录即可，在toolbox选择相应模型。

**Comment by jthinking** [comment]
但是感觉没有自带的syne这个模型效果好，我是哪里没弄对吗

**Comment by KuangDD** [comment]
智浪淘沙训练和分享的模型是用开源数据训练的，开源数据本身就稂莠不齐，所以是没有syne的模型音质好的。

不过这个模型说话人多，能够更好一句话模拟人说话。

**Comment by jthinking** [comment]
明白了
