### ISSUE TITLE
error: Invalid file: PosixPath('../data/samples/biaobei/wav/000019.wav')

### ISSUE THREAD

**Issue by beiliubei** [KuangDD/zhrtvc#75]
执行 python synthesizer_preprocess_audio.py 出错

Python 3.7.9
librosa 0.8.0

估计是 librosa版本太高；

切换使用 requirements_with_version.txt 再试下

**Comment by xuexidi** [comment]
网上说貌似是Python版本的问题，在Py35和py36上没这个问题，我目前用的是py36，没这个问题

**Comment by beiliubei** [comment]
> 网上说貌似是Python版本的问题，在Py35和py36上没这个问题，我目前用的是py36，没这个问题

![image](https://user-images.githubusercontent.com/1127875/104711617-8f6fab00-575c-11eb-936a-40ffa0be56ce.png)
改了下这个文件可以了
