### ISSUE TITLE
请问是否有预训练的speaker embedding模型？

### ISSUE THREAD

**Issue by JohnHerry** [KuangDD/zhrtvc#91]
如题，请问是否有中文环境的 speaker embedding模型？跟论文一样的64维输出的?
另外本工程所用梅尔谱参数跟 tacotron的有什么差异吗？为什么开源预训练的waveglow vocoder不能拿来直接用？

**Comment by KuangDD** [comment]
有iwater的用中文开源数据集训练的encoder模型，可以试试。

链接: https://pan.baidu.com/s/1QIDAhB5Z5g-Aee3tfTuz7g 提取码: whnb 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v2的分享

**Comment by JohnHerry** [comment]
感谢！
